version: '3'
services:
  # App container
  app:
    build:
      context: .
      dockerfile: contrib/docker/Dockerfile.apache
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - app-storage:/var/www/storage
      - app-bootstrap:/var/www/bootstrap
      - "./daybreak_prod.sqlite:/var/www/daybreak_prod.sqlite"
      - "./.env:/var/www/.env"
    ports:
      - "80:80"

volumes:
  app-storage:
  app-bootstrap:
